# Generated by Django 5.2.6 on 2025-09-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.CharField(max_length=10),
        ),
    ]
