# Generated by Django 5.2.6 on 2025-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_cachorro_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.CharField(),
        ),
    ]
