# Generated by Django 5.2.6 on 2025-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_cachorro_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='nome',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.CharField(max_length=10),
        ),
    ]
